const $=s=>document.querySelector(s);
const paths={pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',book:'<path d="M3 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H3V4Zm18 0h-6a3 3 0 0 0-3 3v14a4 4 0 0 1 4-2h5V4Z"/>',food:'<path d="M4 3v6a3 3 0 0 0 6 0V3M7 3v18M20 21V3c-5 3-5 10 0 10"/>',bus:'<rect x="4" y="3" width="16" height="16" rx="3"/><path d="M4 11h16M7 19v3m10-3v3M7 15h1m8 0h1M8 6h8"/>',home:'<path d="m3 10 9-7 9 7v11H3V10Zm6 11v-8h6v8"/>',academic:'<path d="m2 8 10-5 10 5-10 5L2 8Zm4 3v7l6 3 6-3v-7m4-3v9"/>',parking:'<path d="M8 21V3h6a5 5 0 0 1 0 10H8"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||paths.pin}</svg>`;
const meta={'Places':['pin','#307789','#e8f3f5'],'Libraries':['book','#5874b6','#edf0fa'],'Food & drink':['food','#d17c38','#fff1e5'],'Bus stops':['bus','#328574','#e8f4ef'],'Residences':['home','#9871a2','#f4eef6'],'Lecture theatres':['academic','#60899c','#eef4f6'],'Academic':['academic','#637992','#eef1f7'],'Parking':['parking','#7d8295','#f0f1f5']};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const campuses={kent:{center:[103.776,1.298],zoom:15.4},utown:{center:[103.7734,1.3056],zoom:16.3},bukit:{center:[103.817,1.3195],zoom:16},outram:{center:[103.833,1.279],zoom:16}};
const essentials=['Central Library','University Town','The Deck','Stephen Riady Centre','Education Resource Centre','Lee Kong Chian Natural History Museum','NUS Museum','Yusof Ishak House','Frontier','UTown Residence'];
let places=[],markers=[],map,selected=null,category='All',savedView=false,saved=new Set(),flat=false,dataReady=false;
try{saved=new Set(JSON.parse(localStorage.getItem('nus-saved')||'[]'))}catch{}
function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500)}
function filtered(){let q=$('#search').value.trim().toLowerCase();return places.filter(p=>(category==='All'||p.category===category)&&(!savedView||saved.has(p.id))&&(!q||`${p.name} ${p.alias} ${p.address} ${p.category}`.toLowerCase().includes(q))).sort((a,b)=>{let ai=essentials.indexOf(a.name),bi=essentials.indexOf(b.name);return (ai<0?999:ai)-(bi<0?999:bi)||a.name.localeCompare(b.name)})}
function render(){if(map?.getLayer('selected-building'))map.setFilter('selected-building',['==',['get','id'],selected?.buildingId||'']);let list=filtered(),q=$('#search').value.trim();$('#count').textContent=`${list.length} places`;$('#list-title').textContent=savedView?'Your saved places':q?'Search results':category==='All'?'Campus essentials':category;$('#save-count').textContent=saved.size;$('#clear').hidden=!q;$('#results').innerHTML=list.slice(0,100).map(p=>{let [i,c,b]=meta[p.category];return `<button class="place-row ${selected?.id===p.id?'selected':''}" data-id="${p.id}"><span class="place-icon" style="--color:${c};--pale:${b}">${icon(i)}</span><span class="place-copy"><strong>${esc(p.name)}</strong><small>${esc(p.category)} · ${esc(p.campus.includes('UTOWN')||p.campus==='University Town'?'University Town':p.campus.replace(' Campus',''))}</small></span><span class="chevron">›</span></button>`}).join('')||`<div class="empty">${savedView?'No saved places yet. Select a place and tap Save to keep it here.':'No places found. Try a building name, LT code, or another category.'}</div>`;if(list.length>100)$('#results').insertAdjacentHTML('beforeend','<p class="empty">Showing the first 100 places. Search to narrow the list.</p>');$('#results').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>showPlace(places.find(p=>p.id===b.dataset.id)));renderMarkers(list)}
function renderMarkers(list){if(!map)return;markers.forEach(m=>m.remove());markers=[];let q=$('#search').value.trim();let shown=(q||category!=='All'||savedView?list:places.filter(p=>essentials.includes(p.name)||p.category==='Libraries'||p.category==='Residences')).slice(0,70);if(selected&&!shown.some(p=>p.id===selected.id))shown.push(selected);shown.forEach(p=>{let el=document.createElement('button');el.className=`pin ${essentials.includes(p.name)?'featured':''} ${selected?.id===p.id?'chosen':''}`;el.style.setProperty('--color',meta[p.category][1]);el.setAttribute('aria-label',p.name);el.innerHTML=icon(meta[p.category][0])+`<span class="pin-label">${esc(p.name)}</span>`;el.onclick=()=>showPlace(p);markers.push(new StreetsMarker({element:el}).setLngLat([p.lng,p.lat]).addTo(map))})}
function showPlace(p){closeSearch();selected=p;let d=$('#detail');d.hidden=false;d.innerHTML=`<button class="close" aria-label="Close place details">×</button><div class="detail-category">${esc(p.category)}</div><h2>${esc(p.name)}</h2><p>${esc(p.address||p.campus)}</p>${p.buildingId?energyPanel(p):''}<div class="actions"><a target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}&travelmode=walking">↗ Walking directions</a><button class="save-button" aria-pressed="${saved.has(p.id)}">${saved.has(p.id)?'♥ Saved':'♡ Save'}</button></div><div class="detail-note">Directions open in Google Maps</div>`;d.querySelector('.close').onclick=()=>{selected=null;d.hidden=true;render()};d.querySelector('.save-button').onclick=()=>{saved.has(p.id)?saved.delete(p.id):saved.add(p.id);try{localStorage.setItem('nus-saved',JSON.stringify([...saved]))}catch{toast('Saved for this session only; browser storage is unavailable.')}showPlace(p)};map?.flyTo({center:[p.lng,p.lat],zoom:17,pitch:flat?0:48,duration:900,padding:{bottom:100}});render()}
const filterNames=[['All','pin','All places'],['Libraries','book','Libraries'],['Food & drink','food','Food & drink'],['Bus stops','bus','Bus stops'],['Lecture theatres','academic','Lecture theatres'],['Residences','home','Residences'],['Parking','parking','Parking']];
$('#categories').innerHTML=filterNames.map(([v,i,label])=>`<button class="chip ${v==='All'?'active':''}" data-category="${v}" aria-pressed="${v==='All'}">${icon(i)}${label}</button>`).join('');$('#categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;$('#categories').querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});render()});
function openSearch(){ $('#search-panel').hidden=false; $('#search').setAttribute('aria-expanded','true') }
function closeSearch(){ $('#search-panel').hidden=true; $('#search').setAttribute('aria-expanded','false') }
$('#search').onfocus=openSearch;
$('#search').onclick=openSearch;
$('#search').oninput=()=>{openSearch();render()};
document.addEventListener('pointerdown',e=>{if(!$('#search-overlay').contains(e.target))closeSearch()});
$('#search-overlay').addEventListener('focusout',()=>setTimeout(()=>{if(!$('#search-overlay').contains(document.activeElement))closeSearch()},0));
$('#search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();openSearch();$('#results button')?.focus()}if(e.key==='Enter'){const first=filtered()[0];if(first)showPlace(first)}});
$('#search-panel').addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp'].includes(e.key))return;const buttons=[...$('#results').querySelectorAll('button')];const i=buttons.indexOf(document.activeElement);if(i>=0){e.preventDefault();buttons[Math.max(0,Math.min(buttons.length-1,i+(e.key==='ArrowDown'?1:-1)))]?.focus()}});
$('#clear').onclick=()=>{$('#search').value='';render();$('#search').focus()};document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){closeSearch();$('#search').blur();$('#detail').hidden=true;selected=null;render()}});
function tab(savedTab){savedView=savedTab;$('#explore').setAttribute('aria-selected',!savedTab);$('#saved').setAttribute('aria-selected',savedTab);render()}$('#explore').onclick=()=>tab(false);$('#saved').onclick=()=>tab(true);
$('#about').onclick=()=>$('#about-dialog').showModal();$('#close-about').onclick=()=>$('#about-dialog').close();$('#about-dialog').onclick=e=>{if(e.target===$('#about-dialog')&&e.offsetX<0)$('#about-dialog').close()};
function goCampus(){let p=campuses[$('#campus').value];map?.flyTo({...p,pitch:flat?0:45,bearing:-18,padding:{bottom:0},duration:1000});$('#detail').hidden=true;selected=null;render()}$('#campus').onchange=goCampus;$('#reset').onclick=goCampus;$('#zoom-in').onclick=()=>map?.zoomIn();$('#zoom-out').onclick=()=>map?.zoomOut();function view(isFlat){flat=isFlat;$('#view2d').classList.toggle('active',flat);$('#view3d').classList.toggle('active',!flat);$('#view2d').setAttribute('aria-pressed',flat);$('#view3d').setAttribute('aria-pressed',!flat);map?.easeTo({pitch:flat?0:50,bearing:flat?0:-18,duration:600})}$('#view2d').onclick=()=>view(true);$('#view3d').onclick=()=>view(false);
$('#locate').onclick=()=>{if(!navigator.geolocation){toast('Location is unavailable in this browser.');return}toast('Finding your location…');navigator.geolocation.getCurrentPosition(p=>{if(!map)return;new StreetsMarker({color:'#237bdb'}).setLngLat([p.coords.longitude,p.coords.latitude]).addTo(map);map.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:16});toast('Your location is shown in blue.')},()=>toast('Location could not be accessed. You can still search for any campus place.'),{timeout:10000})};
let buildingData={type:'FeatureCollection',features:[]};
function pointInRing(p,r){let c=false;for(let i=0,j=r.length-1;i<r.length;j=i++){let a=r[i],b=r[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])c=!c}return c}
function energyPanel(p){
 let hash=2166136261;for(const ch of p.buildingId){hash=Math.imul(hash^ch.charCodeAt(0),16777619)>>>0}const total=8500+hash%218000;const daily=Math.round(total/30);return `<section class="energy-panel" aria-label="Demo building energy consumption"><div class="energy-heading"><span>ϟ</span> Total energy consumption <b class="demo-label">DEMO</b></div><div class="energy-value">${total.toLocaleString('en-SG')} <span>kWh</span></div><div class="energy-disconnected">September 2026 · Sample month</div><dl><div><dt>Daily average</dt><dd>${daily.toLocaleString('en-SG')} kWh</dd></div><div><dt>Data source</dt><dd>Simulated dataset</dd></div></dl><p>Illustrative demo only. Not actual NUS energy consumption.</p></section>`}
const campusReady=Promise.all(['places.json','buildings.geojson','campus-boundaries.geojson','building-details.geojson','trees.geojson'].map(url=>fetch(url).then(r=>{if(!r.ok)throw Error(url);return r.json()}))).then(([data,buildings,bounds,details,trees])=>{buildingData=buildings;places=data.map(p=>{const b=buildings.features.find(f=>pointInRing([p.lng,p.lat],f.geometry.coordinates[0]));return b?{...p,buildingId:b.properties.id}:p});for(const b of buildings.features){if(!places.some(p=>p.buildingId===b.properties.id && p.name.toLowerCase()===b.properties.name.toLowerCase()))places.push({id:b.properties.id,buildingId:b.properties.id,name:b.properties.name==='NUS building'?`NUS building · ${b.properties.id.replace('osm-','')}`:b.properties.name,lng:b.properties.lng,lat:b.properties.lat,category:'Places',campus:'NUS',address:'NUS campus',alias:b.properties.id})}dataReady=true;render();return {buildings,bounds,details,trees}}).catch(e=>{$('#results').innerHTML='<div class="empty">Campus data could not load. Refresh to retry.</div>';$('#map-status').textContent='Campus building data is unavailable. Refresh to retry.';throw e});
map=new StreetsMap();
map.onInteract=closeSearch;
map.onReady=()=>{$('#map-status').textContent='Loading campus buildings…';campusReady.then(({buildings})=>map.send({action:'buildings',features:buildings.features}));render()};
map.onBuilding=(id)=>{const bid='osm-'+id;const p=places.find(p=>p.buildingId===bid)||places.find(p=>p.id===bid);if(p)showPlace(p);else toast('No campus energy record is linked to this building.')};
campusReady.then(()=>render());
setTimeout(()=>{if(!map.ready)$('#map-status').textContent='Loading Streets GL textures and terrain…'},10000);


